### ISSUE TITLE
Remove search from tabview

### ISSUE THREAD

**Issue by dbay920** [dbay920/phn-app#45]
Seems redundant with search in actionbar as well.
My attempts to remove it are causing app to be unstable :/

**Comment by elimin8r** [comment]
@dbay920 it is probably going to be way easier to remove it from the actionbar than removing it from the tabview.

**Comment by dbay920** [comment]
I see, guess it is integral to the view. Hold off on this for now, but let me know how hard it would be to reorder tab views so search is last.

**Comment by elimin8r** [comment]
that should be fairly easy
