### ISSUE TITLE
iOS provider images not showing

### ISSUE THREAD

**Issue by dbay920** [dbay920/phn-app#51]
Provider images not displaying on Provider Detail view for iOS only, please look into this.

**Comment by elimin8r** [comment]
im seeing pictures on ios on provider detail. is there a particular provider thats not working

**Comment by dbay920** [comment]
Maybe branch-related, creating pull request

David Bayley
Web Development/Marketing Specialist
Corporate & Community Relations
63 Pitt Street
Sharon, PA 16146
(724) 342-3002 Ext. 1545


[cid:image001.png@01CFCB67.2DC307E0]

**Comment by elimin8r** [comment]
did merging the branch resolve the issue?

**Comment by dbay920** [comment]
This is now fixed, thought I closed this
